### ISSUE TITLE
How to add multiple dependencies simultaneously?

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [unjs/nypm#105]
### Describe the feature

It's very common and pretty basic to want to install multiple dependencies simultaneously. I was very surprised that doing: `addDevDependency("dep1 dep2 dep3")` fails. Nypm only seem to work doing `addDevDependency("dep1")`. This is a deal-breaker for me. I expected this to work out-of-the-box to be honest. Any chance this gets implemented?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by DamianGlowala** [comment]
Happy to address this issue. Which of the following do we prefer?

- `addDependency('dep1 dep2 dep3')`
- `addDependency(['dep1', 'dep2', 'dep3'])`
- supporting both

cc @pi0

**Comment by DamianGlowala** [comment]
Thanks for your feedback! Let's wait for Pooya to confirm this is the direction we all agree on.

I'm not a big fan of having `addDevDependency` either knowing that `addDependency` supports the `dev: true` option, but AFAIK it was added for convenience. Maybe this could change in the future with it first being deprecated and then eventually removed in a major release, but I'm definitely not the one to decide on that ;)
