### ISSUE TITLE
installDependencies frozen lockfile option

### ISSUE THREAD

**Issue by RyanClementsHax** [unjs/nypm#115]
### Describe the feature

It would be handy to have `installDependencies` have an option that forces the underlying install command to install only what is in the lock file.

My use case is I'm using `npym` when creating starter projects from a template. Installing exact dependencies helps make the application generation deterministic and reproduceable.

It could look something like the following.

```ts
await installDependencies({
  cwd: workspacePath,
  frozenLockFile: true, // defaults to false
});
```

This would then translate to the following install commands.

- `pnpm install --frozen-lockfile` https://pnpm.io/cli/install#--frozen-lockfile
- `yarn install --forzen-lockfile` https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
- `npm ci` https://docs.npmjs.com/cli/v10/commands/npm-ci

I've considered some other names for this option in case `frozenLockFile` isn't ideal.
- `useLockFile`
- `frozen`
- `ci`

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR welcome. As this is commonly supported amongst all supported PMs now.

**Comment by RyanClementsHax** [comment]
Excellent. I'd be happy to implement it.
