### ISSUE TITLE
Replace `execa` with `tinyexec`

### ISSUE THREAD

**Issue by SukkaW** [unjs/nypm#172]
### Describe the feature

`tinyexec` is a well-maintained lightweight command executor that we can use to replace `execa`: https://github.com/tinylibs/tinyexec. It is also easier to use (providing a simple API).

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
nypm switched to tinyexec since [v0.4.0](https://github.com/unjs/nypm/releases/tag/v0.4.0)
