### ISSUE TITLE
feat(types): improve `PackageManager` type

### ISSUE THREAD

**Issue by Colonel-Sandvich** [unjs/nypm#173]
### Describe the feature

Currently `PackageManager.lockFile` is `undefined | string | string[]` but currently the corresponding field in [`package-manager.ts`](https://github.com/unjs/nypm/blob/main/src/package-manager.ts#L35) is never undefined. Types can be improved here to remove this

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
https://github.com/unjs/nypm/pull/174#issuecomment-2563629479
