### ISSUE TITLE
API support progress

### ISSUE THREAD

**Issue by pi0** [unjs/nypm#5]
Package manager commands:

- [x] `installDependency`
- [x] `removeDependency`
- [ ] `installDevdependency` / `removeDevDependency` (shortcut for `{ dev: true }`)
- [ ] `getPackageManagerInfo` (with real version)

Utilities:

- [ ] `sortPackageJSON` (https://github.com/unjs/nypm/issues/6)
- [ ] `getPackageInfo` (https://github.com/unjs/nypm/issues/7)
- [ ] `prompt` (https://github.com/unjs/nypm/issues/10)

**Comment by lzm0x219** [comment]
mark
