### ISSUE TITLE
Support sorting package.json 

### ISSUE THREAD

**Issue by pi0** [unjs/nypm#6]
`sortPackageJSON` (later `nypm sort`) support sorting with [keithamus/sort-package-json](https://github.com/keithamus/sort-package-json)

**Comment by cpreston321** [comment]
@pi0 Questions

- I assume you want to this override the current `package.json` using this command correct?
- What are some use cases this would used in? I kind of want to understand the different cases to better support this.

Thanks 💚

**Comment by pi0** [comment]
- Yes updating package.json
- Limiting package mainly by users.

**Comment by pi0** [comment]
https://github.com/unjs/nypm/pull/60#issuecomment-1597020438

**Comment by pi0** [comment]
We might revisit this by using `npx sort-package-json@latest` as a wrapper.
